### ISSUE TITLE
Program crashes 5 seconds after any page other than the google home pages is opened

### ISSUE THREAD

**Issue by Geoffrey-Hash** [sagargoswami2001/Simple-Web-Browser-Using-Python#1]
specifically the error is 
Faulting application name: pythonw.exe, version: 3.12.2150.1013, time stamp: 0x65c2a4c7
Faulting module name: Qt5Core.dll, version: 5.15.2.0, time stamp: 0x5fa4dd3b
Exception code: 0xc0000409

**Comment by sagargoswami2001** [comment]
I will check

**Comment by Geoffrey-Hash** [comment]
So it turns out Pycharms packages just broke my preexisting PyQT5 module install. no issue with the program itself.
